# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='corpo',
            field=models.TextField(blank=True, verbose_name='Corpo da mat\xe9ria'),
        ),
    ]
